# Generated by Django 4.0.4 on 2022-05-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('anons', models.CharField(max_length=200, verbose_name='Анонс')),
                ('content', models.TextField(verbose_name='Статья')),
                ('date', models.DateTimeField(blank=True, verbose_name='Дата публикации')),
                ('meta', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=75)),
                ('join_time', models.CharField(max_length=50)),
            ],
        ),
    ]
