# Generated by Django 4.0.4 on 2022-05-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=75)),
                ('date_join', models.DateTimeField(blank=True, verbose_name='Дата регистрации')),
            ],
        ),
    ]
