# Generated by Django 4.0.4 on 2022-05-23 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_articles_img_anons_articles_img_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='img_anons',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='img_content',
        ),
    ]
