# Generated by Django 4.0.4 on 2022-05-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_articles_img_anons_articles_img_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='img_anons',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='articles',
            name='img_content',
            field=models.CharField(max_length=300),
        ),
    ]
