# Generated by Django 4.0.4 on 2022-05-24 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
        ('app', '0008_alter_articles_img_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, verbose_name='Дата написания')),
                ('content', models.TextField(verbose_name='Текст коментария')),
                ('author_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='registration.user', verbose_name='Автор коментария')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_articles', to='app.articles')),
            ],
        ),
    ]
